- <username> = 'username'
- <password> = 'password'

- <caseId> = '159'

- <session> = Reveal_Login_Get username: <username> password: <password> 
- <userId> = <session>["UserId"]
- log $"UserId: {<userId>}" 
- <LoginSessionId> = <session>["LoginSessionId"]

- log (Reveal_FieldProfile_Get caseId: <caseID>  InControlAuthToken:  <LoginSessionId>)
- log EntityFormat (Reveal_Field_GetAllFields caseId: <caseID>  InControlAuthToken:  <LoginSessionId>)