/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Sequence",
  "tagline": "Automate the mundane",
  "url": "https://sequence.sh",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.png",
  "organizationName": "sequence",
  "projectName": "sequence-docs",
  "customFields": {
    "homeTitle": "End-to-end automation for forensics and ediscovery",
    "description": "Flexible and powerful open-source automation toolkit for creating repeatable, predictable, and defensible end-to-end forensic and ediscovery workflows.",
    "downloads": "https://get.sequence.sh"
  },
  "staticDirectories": [
    "static",
    "playground"
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "docs",
          "routeBasePath": "docs",
          "sidebarPath": "/Users/jim/Desktop/github/soda/sidebarsDocs.js",
          "editUrl": "https://gitlab.com/sequence/sequence-docs/edit/main",
          "versions": {
            "current": {
              "label": "v0.19.0-alpha 🚧"
            }
          }
        },
        "blog": {
          "path": "blog",
          "routeBasePath": "blog",
          "editUrl": "https://gitlab.com/sequence/sequence-docs/edit/main",
          "postsPerPage": 10,
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright © 2025 Reductech Ltd"
          },
          "blogSidebarCount": "ALL"
        },
        "theme": {
          "customCss": "/Users/jim/Desktop/github/soda/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "steps",
        "path": "steps",
        "routeBasePath": "steps",
        "sidebarPath": "/Users/jim/Desktop/github/soda/sidebarsSteps.js",
        "editUrl": "https://gitlab.com/sequence/sequence-docs/edit/main",
        "versions": {
          "current": {
            "label": "v0.19.0-alpha 🚧"
          }
        }
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "Sequence",
      "logo": {
        "alt": "Sequence Logo",
        "src": "img/sequence_icon_light_opt.svg",
        "srcDark": "img/sequence_icon_dark_opt.svg"
      },
      "hideOnScroll": true,
      "items": [
        {
          "type": "docsVersion",
          "docId": "intro",
          "position": "left",
          "label": "Documentation"
        },
        {
          "type": "docsVersion",
          "docsPluginId": "steps",
          "docId": "all",
          "position": "left",
          "label": "Steps"
        },
        {
          "to": "blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "/playground",
          "label": "Playground",
          "position": "left"
        },
        {
          "label": "Download",
          "href": "/download",
          "position": "right",
          "className": "button button-download button--primary button--lg"
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://gitlab.com/sequence",
          "position": "right",
          "className": "header-gitlab-link",
          "aria-label": "GitLab Repository"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learn",
          "items": [
            {
              "label": "Connectors",
              "to": "/docs/quick-start#connectors"
            },
            {
              "label": "Installation and Configuration",
              "to": "/docs/quick-start"
            },
            {
              "label": "Sequence Configuration Language",
              "to": "/docs/sequence-configuration-language"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Check out the Source Code",
              "href": "https://gitlab.com/sequence"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/sequence_sh"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Search",
              "href": "/search"
            },
            {
              "label": "Reductech",
              "href": "https://reductech.io"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Reductech Ltd. Built with <a href=\"https://docusaurus.io\" target=\"_blank\" rel=\"noopener\">Docusaurus</a>. Sequence is a UK registered trademark of Reductech Ltd."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#000000",
          "backgroundColor": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(0, 128, 0)"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "rgb(0, 112, 193)"
            }
          },
          {
            "types": [
              "number",
              "variable",
              "inserted"
            ],
            "style": {
              "color": "rgb(9, 134, 88)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(0, 0, 0)"
            }
          },
          {
            "types": [
              "constant",
              "char"
            ],
            "style": {
              "color": "rgb(129, 31, 63)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(128, 0, 0)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 0, 0)"
            }
          },
          {
            "types": [
              "deleted",
              "string"
            ],
            "style": {
              "color": "rgb(163, 21, 21)"
            }
          },
          {
            "types": [
              "changed",
              "punctuation"
            ],
            "style": {
              "color": "rgb(4, 81, 165)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "rgb(0, 0, 255)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(38, 127, 153)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "powershell",
        "csharp"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "CKHLUDXFLE",
      "apiKey": "eefd45babb6696e6fc0fe9943a9d631c",
      "indexName": "sequence-sh",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
